/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ui_btjava;

/**
 *
 * @author PQMIT
 */

public class UI_BT extends javax.swing.JFrame {
    //public static int Control = 0;
    public int control;

    /**
     * Creates new form UI_BT
     */
    public UI_BT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        t1b1 = new javax.swing.JButton();
        t1b2 = new javax.swing.JButton();
        t1b3 = new javax.swing.JButton();
        t1b4 = new javax.swing.JButton();
        t1b5 = new javax.swing.JButton();
        t2b1 = new javax.swing.JButton();
        t3b1 = new javax.swing.JButton();
        t4b1 = new javax.swing.JButton();
        Run = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextArea2 = new javax.swing.JTextArea();
        t1b6 = new javax.swing.JButton();
        t1b7a = new javax.swing.JButton();
        t1b7b = new javax.swing.JButton();
        t1b7c = new javax.swing.JButton();
        t1b7d = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        text_nhap = new javax.swing.JTextField();
        t1b8 = new javax.swing.JButton();
        label_nhap = new javax.swing.JButton();
        t1b9 = new javax.swing.JButton();
        t1b10 = new javax.swing.JButton();
        t1b11 = new javax.swing.JButton();
        t1b12 = new javax.swing.JButton();
        t2b2 = new javax.swing.JButton();
        t2b3 = new javax.swing.JButton();
        t2b4 = new javax.swing.JButton();
        text_nhap2 = new javax.swing.JTextField();
        t3b2 = new javax.swing.JButton();
        btn_nhap = new javax.swing.JButton();
        t3b3 = new javax.swing.JButton();
        t3b4 = new javax.swing.JButton();
        t3b5 = new javax.swing.JButton();
        t3b6 = new javax.swing.JButton();
        t3b7 = new javax.swing.JButton();
        t3b8 = new javax.swing.JButton();
        t3b9 = new javax.swing.JButton();
        t3b10 = new javax.swing.JButton();
        t3b11 = new javax.swing.JButton();
        t3b12 = new javax.swing.JButton();
        t4b2 = new javax.swing.JButton();
        t4b3 = new javax.swing.JButton();
        t4b4 = new javax.swing.JButton();
        t4b5 = new javax.swing.JButton();
        t4b6 = new javax.swing.JButton();
        t4b7 = new javax.swing.JButton();
        t4b8 = new javax.swing.JButton();
        t4b9 = new javax.swing.JButton();
        t4b10 = new javax.swing.JButton();
        t4b11 = new javax.swing.JButton();
        t4b12 = new javax.swing.JButton();
        t4b13 = new javax.swing.JButton();
        t4b14 = new javax.swing.JButton();
        t4b15 = new javax.swing.JButton();
        t4b16 = new javax.swing.JButton();
        btn_nhap1 = new javax.swing.JButton();
        text_nhap3 = new javax.swing.JTextField();
        btn_nhap2 = new javax.swing.JButton();
        text_nhap4 = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        t1b1.setText("t1b1");
        t1b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1b1ActionPerformed(evt);
            }
        });

        t1b2.setText("t1b2");
        t1b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1b2ActionPerformed(evt);
            }
        });

        t1b3.setText("t1b3");
        t1b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1b3ActionPerformed(evt);
            }
        });

        t1b4.setText("t1b4");
        t1b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1b4ActionPerformed(evt);
            }
        });

        t1b5.setText("t1b5");
        t1b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1b5ActionPerformed(evt);
            }
        });

        t2b1.setText("t2b1");
        t2b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2b1ActionPerformed(evt);
            }
        });

        t3b1.setText("t3b1");
        t3b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3b1ActionPerformed(evt);
            }
        });

        t4b1.setText("t4b1");
        t4b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4b1ActionPerformed(evt);
            }
        });

        Run.setText("Run");
        Run.setPreferredSize(new java.awt.Dimension(100, 25));
        Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunActionPerformed(evt);
            }
        });

        TextArea1.setColumns(20);
        TextArea1.setRows(5);
        TextArea1.setMaximumSize(new java.awt.Dimension(204, 84));
        jScrollPane2.setViewportView(TextArea1);

        TextArea2.setColumns(20);
        TextArea2.setRows(5);
        jScrollPane3.setViewportView(TextArea2);

        t1b6.setText("t1b6");
        t1b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1b6ActionPerformed(evt);
            }
        });

        t1b7a.setText("t1b7a");
        t1b7a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1b7aActionPerformed(evt);
            }
        });

        t1b7b.setText("t1b7b");
        t1b7b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1b7bActionPerformed(evt);
            }
        });

        t1b7c.setText("t1b7c");
        t1b7c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1b7cActionPerformed(evt);
            }
        });

        t1b7d.setText("t1b7d");
        t1b7d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1b7dActionPerformed(evt);
            }
        });

        text_nhap.setFont(text_nhap.getFont().deriveFont(text_nhap.getFont().getStyle() | java.awt.Font.BOLD, text_nhap.getFont().getSize()+6));
        text_nhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nhapActionPerformed(evt);
            }
        });

        t1b8.setText("t1b8");
        t1b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1b8ActionPerformed(evt);
            }
        });

        label_nhap.setText("label_nhap");
        label_nhap.setPreferredSize(new java.awt.Dimension(100, 25));
        label_nhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_nhapActionPerformed(evt);
            }
        });

        t1b9.setText("t1b9");
        t1b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1b9ActionPerformed(evt);
            }
        });

        t1b10.setText("t1b10");
        t1b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1b10ActionPerformed(evt);
            }
        });

        t1b11.setText("t1b11");
        t1b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1b11ActionPerformed(evt);
            }
        });

        t1b12.setText("t1b12");
        t1b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1b12ActionPerformed(evt);
            }
        });

        t2b2.setText("t2b2");
        t2b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2b2ActionPerformed(evt);
            }
        });

        t2b3.setText("t2b3");
        t2b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2b3ActionPerformed(evt);
            }
        });

        t2b4.setText("t2b4");
        t2b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2b4ActionPerformed(evt);
            }
        });

        text_nhap2.setFont(text_nhap2.getFont().deriveFont(text_nhap2.getFont().getStyle() | java.awt.Font.BOLD, text_nhap2.getFont().getSize()+6));
        text_nhap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nhap2ActionPerformed(evt);
            }
        });

        t3b2.setText("t3b2");
        t3b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3b2ActionPerformed(evt);
            }
        });

        btn_nhap.setText("btn_nhap");
        btn_nhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhapActionPerformed(evt);
            }
        });

        t3b3.setText("t3b3");
        t3b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3b3ActionPerformed(evt);
            }
        });

        t3b4.setText("t3b4");
        t3b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3b4ActionPerformed(evt);
            }
        });

        t3b5.setText("t3b5");
        t3b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3b5ActionPerformed(evt);
            }
        });

        t3b6.setText("t3b6");
        t3b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3b6ActionPerformed(evt);
            }
        });

        t3b7.setText("t3b7");
        t3b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3b7ActionPerformed(evt);
            }
        });

        t3b8.setText("t3b8");
        t3b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3b8ActionPerformed(evt);
            }
        });

        t3b9.setText("t3b9");
        t3b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3b9ActionPerformed(evt);
            }
        });

        t3b10.setText("t3b10");
        t3b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3b10ActionPerformed(evt);
            }
        });

        t3b11.setText("t3b11");
        t3b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3b11ActionPerformed(evt);
            }
        });

        t3b12.setText("t3b12");
        t3b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3b12ActionPerformed(evt);
            }
        });

        t4b2.setText("t4b2");
        t4b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4b2ActionPerformed(evt);
            }
        });

        t4b3.setText("t4b3");
        t4b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4b3ActionPerformed(evt);
            }
        });

        t4b4.setText("t4b4");
        t4b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4b4ActionPerformed(evt);
            }
        });

        t4b5.setText("t4b5");
        t4b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4b5ActionPerformed(evt);
            }
        });

        t4b6.setText("t4b6");
        t4b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4b6ActionPerformed(evt);
            }
        });

        t4b7.setText("t4b7");
        t4b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4b7ActionPerformed(evt);
            }
        });

        t4b8.setText("t4b8");
        t4b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4b8ActionPerformed(evt);
            }
        });

        t4b9.setText("t4b9");
        t4b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4b9ActionPerformed(evt);
            }
        });

        t4b10.setText("t4b10");
        t4b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4b10ActionPerformed(evt);
            }
        });

        t4b11.setText("t4b11");
        t4b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4b11ActionPerformed(evt);
            }
        });

        t4b12.setText("t4b12");
        t4b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4b12ActionPerformed(evt);
            }
        });

        t4b13.setText("t4b13");
        t4b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4b13ActionPerformed(evt);
            }
        });

        t4b14.setText("t4b14");
        t4b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4b14ActionPerformed(evt);
            }
        });

        t4b15.setText("t4b15");
        t4b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4b15ActionPerformed(evt);
            }
        });

        t4b16.setText("t4b16");
        t4b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4b16ActionPerformed(evt);
            }
        });

        btn_nhap1.setText("btn_nhap1");
        btn_nhap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhap1ActionPerformed(evt);
            }
        });

        text_nhap3.setFont(text_nhap3.getFont().deriveFont(text_nhap3.getFont().getStyle() | java.awt.Font.BOLD, text_nhap3.getFont().getSize()+6));
        text_nhap3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nhap3ActionPerformed(evt);
            }
        });

        btn_nhap2.setText("btn_nhap2");
        btn_nhap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhap2ActionPerformed(evt);
            }
        });

        text_nhap4.setFont(text_nhap4.getFont().deriveFont(text_nhap4.getFont().getStyle() | java.awt.Font.BOLD, text_nhap4.getFont().getSize()+6));
        text_nhap4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nhap4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t1b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t1b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t1b4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t1b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t1b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(t1b6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t1b7c)
                            .addComponent(t1b8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t1b9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t1b11)
                            .addComponent(t1b12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t2b1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t3b1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t2b2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t3b2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t2b3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t3b3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t2b4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(t3b8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(t4b8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(t3b7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(t4b7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(t3b6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(t4b6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(t3b5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(t4b5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(t3b4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(t4b4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(t4b1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(t3b9)
                                                .addGap(18, 18, 18)
                                                .addComponent(t4b9))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(t3b10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(t4b10))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(t3b11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(t4b11)))
                                        .addComponent(t4b2)
                                        .addComponent(t4b3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(t3b12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(t4b12))
                                        .addComponent(t4b13)
                                        .addComponent(t4b14)
                                        .addComponent(t4b15)
                                        .addComponent(t4b16))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(t1b10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t1b7a, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t1b7d, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t1b7b, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_nhap, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Run, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_nhap, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(text_nhap2, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_nhap, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_nhap2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text_nhap3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_nhap4)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_nhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t1b1)
                            .addComponent(t2b1)
                            .addComponent(t3b1)
                            .addComponent(t4b1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t1b2)
                            .addComponent(t2b2)
                            .addComponent(t3b2)
                            .addComponent(t4b2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t1b3)
                            .addComponent(t2b3)
                            .addComponent(t3b3)
                            .addComponent(t4b3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t1b4)
                            .addComponent(t2b4)
                            .addComponent(t3b4)
                            .addComponent(t4b4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t1b5)
                            .addComponent(t3b5)
                            .addComponent(t4b5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t1b6)
                            .addComponent(t3b6)
                            .addComponent(t4b6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t1b7a)
                            .addComponent(t3b7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_nhap, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_nhap, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_nhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_nhap2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t4b7))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_nhap2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(t3b8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t1b7b)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(text_nhap3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(text_nhap4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_nhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t4b8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t4b9)
                            .addComponent(t3b9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t4b10)
                            .addComponent(t3b10)
                            .addComponent(t1b7c))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t1b7d)
                            .addComponent(t3b11)
                            .addComponent(t4b11)
                            .addComponent(Run, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t4b12)
                            .addComponent(t1b8)
                            .addComponent(t3b12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t4b13)
                            .addComponent(t1b9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t1b10)
                            .addComponent(t4b14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t1b11)
                            .addComponent(t4b15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t1b12)
                            .addComponent(t4b16)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1b1ActionPerformed
        BT t1b1 = new BT();
        TextArea1.setText(""+t1b1.dbt1b1());
        btn_nhap.setText("");
        btn_nhap1.setText("");
        btn_nhap2.setText("");
        control = 101;
    }//GEN-LAST:event_t1b1ActionPerformed

    private void RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunActionPerformed

        switch ( control ) {
    case  101:
        BT t1b1 = new BT();
        TextArea2.setText(""+t1b1.t1b1());
        break;
    case  102:
        BT t1b2 = new BT();
        TextArea2.setText(""+t1b2.t1b2());
        break;
    case  103:
        BT t1b3 = new BT();
        TextArea2.setText(""+t1b3.t1b3());
        break;
    case  104:
        BT t1b4 = new BT();
        TextArea2.setText(""+t1b4.t1b4());
        break;
    case  105:
        BT t1b5 = new BT();
        TextArea2.setText(""+t1b5.t1b5());
        break;
    case  106:
        BT t1b6 = new BT();
        TextArea2.setText(""+t1b6.t1b6());
        break;
    case  1071:
        BT t1b7a = new BT();
        TextArea2.setText(""+t1b7a.t1b7a());
        break;
    case  1072:
        BT t1b7b = new BT();
        TextArea2.setText(""+t1b7b.t1b7b());
        break;
    case  1073:
        BT t1b7c =  new BT();
        TextArea2.setText(""+t1b7c.dbt1b7c());
    case  1074:
        BT t1b7d = new BT();
        TextArea2.setText(""+t1b7d.t1b7d());
        break;
    case  108:
        String N = text_nhap.getText();
        BT t1b8 = new BT();
        t1b8.setN(Integer.parseInt(text_nhap.getText()));
        TextArea2.setText(""+t1b8.t1b8());
        break;
    case  109:
        N = text_nhap.getText();
        BT t1b9 = new BT();
        t1b9.setN(Integer.parseInt(text_nhap.getText()));
        TextArea2.setText(""+t1b9.t1b9());
        break;
    case  1010:
        N = text_nhap.getText();
        BT t1b10 = new BT();
        t1b10.setN(Integer.parseInt(text_nhap.getText()));
        TextArea2.setText(""+t1b10.t1b10());
        break;
    case  1011:
        BT t1b11 = new BT();
        
        TextArea2.setText(""+t1b11.t1b11());
        break;
    case  1012:
        String h = text_nhap.getText();
        BT t1b12 = new BT();
        t1b12.setN(Integer.parseInt(text_nhap.getText()));
        TextArea2.setText(""+t1b12.t1b12());
        break;
    case  201:
        N = text_nhap.getText();
        BT t2b1 = new BT();
        t2b1.setN(Integer.parseInt(text_nhap.getText()));
        TextArea2.setText(""+t2b1.t2b1());
        break;
    case  202:
        N = text_nhap.getText();
        BT t2b2 = new BT();
        t2b2.setN(Integer.parseInt(text_nhap.getText()));
        TextArea2.setText(""+t2b2.t2b2());
        break;
    case  203:
        N = text_nhap.getText();
        BT t2b3 = new BT();
        t2b3.setN(Integer.parseInt(text_nhap.getText()));
        TextArea2.setText(""+t2b3.t2b3());
        break;
    case  204:
        N = text_nhap.getText();
        BT t2b4 = new BT();
        t2b4.setN(Integer.parseInt(text_nhap.getText()));
        TextArea2.setText(""+t2b4.t2b4());
        break;
     case  301:
        N = text_nhap.getText();
        String str = text_nhap4.getText();
        BT t3b1 = new BT();
        t3b1.setN(Integer.parseInt(text_nhap.getText()));
        t3b1.setStr(text_nhap4.getText());
        TextArea2.setText(""+t3b1.t3b1());
        break;
    case  302:
        N = text_nhap.getText();
        str = text_nhap4.getText();
        BT t3b2 = new BT();
        t3b2.setN(Integer.parseInt(text_nhap.getText()));
        t3b2.setStr(text_nhap4.getText());
        TextArea2.setText(""+t3b2.t3b2());
        break;
    case  303:
        N = text_nhap.getText();
        str = text_nhap4.getText();
        BT t3b3 = new BT();
        t3b3.setN(Integer.parseInt(text_nhap.getText()));
        t3b3.setStr(text_nhap4.getText());
        TextArea2.setText(""+t3b3.t3b3());
        break;
    case  304:
        N = text_nhap.getText();
        str = text_nhap4.getText();
        BT t3b4 = new BT();
        t3b4.setN(Integer.parseInt(text_nhap.getText()));
        t3b4.setStr(text_nhap4.getText());
        TextArea2.setText(""+t3b4.t3b4());
        break;
    case  305:
        N = text_nhap.getText();
         str = text_nhap4.getText();
        BT t3b5 = new BT();
        t3b5.setN(Integer.parseInt(text_nhap.getText()));
        t3b5.setStr(text_nhap4.getText());
        TextArea2.setText(""+t3b5.t3b5());
        break;
    case  306:
        N = text_nhap.getText();
         str = text_nhap4.getText();
        BT t3b6 = new BT();
        t3b6.setN(Integer.parseInt(text_nhap.getText()));
        t3b6.setStr(text_nhap4.getText());
        TextArea2.setText(""+t3b6.t3b6());
        break;
    case  307:
        N = text_nhap.getText();
         str = text_nhap4.getText();
        BT t3b7 = new BT();
        t3b7.setN(Integer.parseInt(text_nhap.getText()));
        t3b7.setStr(text_nhap4.getText());
        TextArea2.setText(""+t3b7.t3b7());
        break;
    case  308:
        N = text_nhap.getText();
        str = text_nhap4.getText();
        BT t3b8 = new BT();
        t3b8.setN(Integer.parseInt(text_nhap.getText()));
        t3b8.setStr(text_nhap4.getText());
        TextArea2.setText(""+t3b8.t3b8());
        break;
    case  309:
        N = text_nhap.getText();
        str = text_nhap4.getText();
        String N2 = text_nhap2.getText();
        BT t3b9 = new BT();
        t3b9.setN(Integer.parseInt(text_nhap.getText()));
        t3b9.setN2(Integer.parseInt(text_nhap2.getText()));
        t3b9.setStr(text_nhap4.getText());
        TextArea2.setText(""+t3b9.t3b9());
        break;
    case  3010:
        N = text_nhap.getText();
        str = text_nhap4.getText();
        BT t3b10 = new BT();
        t3b10.setN(Integer.parseInt(text_nhap.getText()));
        t3b10.setStr(text_nhap4.getText());
        TextArea2.setText(""+t3b10.t3b10());
        break;
    case  3011:
        N = text_nhap.getText();
        str = text_nhap4.getText();
        BT t3b11 = new BT();
        t3b11.setN(Integer.parseInt(text_nhap.getText()));
        t3b11.setStr(text_nhap4.getText());
        TextArea2.setText(""+t3b11.t3b11());
        break;
    case  3012:
        N = text_nhap.getText();
        str = text_nhap2.getText();
        N2 = text_nhap3.getText();
        String str2 = text_nhap4.getText();
        BT t3b12 = new BT();
        t3b12.setN(Integer.parseInt(N));
        t3b12.setN2(Integer.parseInt(N2));
        t3b12.setStr(str);
        t3b12.setStr2(str2);
        TextArea2.setText(""+t3b12.t3b12());
        break;
    case  401:
        str = text_nhap.getText();
        BT t4b1 = new BT();
        t4b1.setStr(str);
        TextArea2.setText(""+t4b1.t4b1());
        break;
    case  402:
        str = text_nhap.getText();
        BT t4b2 = new BT();
        t4b2.setStr(str);
        TextArea2.setText(""+t4b2.t4b2());
        break;
    case  403:
         str = text_nhap.getText();
        BT t4b3 = new BT();
        t4b3.setStr(str);
        TextArea2.setText(""+t4b3.t4b3());
        break;
    case  404:
         str = text_nhap.getText();
        BT t4b4 = new BT();
        t4b4.setStr(str);
        TextArea2.setText(""+t4b4.t4b4());
        break;
    case  405:
         str = text_nhap.getText();
        BT t4b5 = new BT();
        t4b5.setStr(str);
        TextArea2.setText(""+t4b5.t4b5());
        break;
    case  406:
         str = text_nhap.getText();
        BT t4b6 = new BT();
        t4b6.setStr(str);
        TextArea2.setText(""+t4b6.t4b6());
        break;
    case  407:
         str = text_nhap.getText();
        BT t4b7 = new BT();
        t4b7.setStr(str);
        TextArea2.setText(""+t4b7.t4b7());
        break;
    case  408:
         str = text_nhap.getText();
        str2 = text_nhap2.getText();
        BT t4b8 = new BT();
        t4b8.setStr(str);
        t4b8.setStr2(str2);
        TextArea2.setText(""+t4b8.t4b8());
        break;
    case  409:
         str = text_nhap.getText();
         N = text_nhap2.getText();
          N2 = text_nhap3.getText();
        BT t4b9 = new BT();
        t4b9.setStr(str);
        t4b9.setN(Integer.parseInt(text_nhap2.getText()));
        t4b9.setN2(Integer.parseInt(text_nhap3.getText()));
        TextArea2.setText(""+t4b9.t4b9());
        break;
    case  4010:
         N = text_nhap.getText();
         str = text_nhap2.getText();
        BT t4b10 = new BT();
        t4b10.setN(Integer.parseInt(N));
        t4b10.setStr(str);
        TextArea2.setText(""+t4b10.t4b10());
        break;
    case  4011:
         N = text_nhap.getText();
         str = text_nhap2.getText();
        BT t4b11 = new BT();
        t4b11.setN(Integer.parseInt(N));
        t4b11.setStr(str);
        TextArea2.setText(""+t4b11.t4b11());
        break;
    case  4012:
         N = text_nhap.getText();
         str = text_nhap2.getText();
        BT t4b12 = new BT();
        t4b12.setN(Integer.parseInt(N));
        t4b12.setStr(str);
        TextArea2.setText(""+t4b12.t4b12());
        break;
    case  4013:
         N = text_nhap.getText();
         str = text_nhap2.getText();
        BT t4b13 = new BT();
        t4b13.setN(Integer.parseInt(N));
        t4b13.setStr(str);
        TextArea2.setText(""+t4b13.t4b13());
        break;
    case  4014:
         N = text_nhap.getText();
        BT t4b14 = new BT();
        t4b14.setN(Integer.parseInt(N));
        TextArea2.setText(""+t4b14.t4b14());
        break;
    case  4015:
         str = text_nhap.getText();
         str2 = text_nhap2.getText();
        String str3 = text_nhap3.getText();
        BT t4b15 = new BT();
        t4b15.setStr(str);
        t4b15.setStr2(str2);
        t4b15.setStr3(str3);
        TextArea2.setText(""+t4b15.t4b15());
        break;
    case  4016:
         str = text_nhap.getText();
         str2 = text_nhap2.getText();
        BT t4b16 = new BT();
        t4b16.setStr(str);
        t4b16.setStr2(str2);
        TextArea2.setText(""+t4b16.t4b16());
        break;
    default:
        // Làm gì đó tại đây ...
}
    }//GEN-LAST:event_RunActionPerformed

    public static void findSNT(int [] arr){
        int num=0;
        for(int i=0; i<arr.length ; i++){
            int counter=0;
            for(num=arr[i]; num>=1 ; num--)
            {
                if(arr[i]%num==0)
                {
                    counter = counter + 1;
                }
            }
            if (counter ==2)
            {
                System.out.println("so nguyen to : "+ arr[i]);
            }
        }           
    };
    private void t1b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1b2ActionPerformed
        BT t1b2 =  new BT();
        TextArea1.setText(""+t1b2.dbt1b2());
        
        control = 102;
    }//GEN-LAST:event_t1b2ActionPerformed

    private void t1b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1b3ActionPerformed
        BT t1b3 =  new BT();
        TextArea1.setText(""+t1b3.dbt1b3());
        control = 103;
    }//GEN-LAST:event_t1b3ActionPerformed

    private void t1b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1b4ActionPerformed
        BT t1b4 =  new BT();
        TextArea1.setText(""+t1b4.dbt1b4());
        control = 104;
    }//GEN-LAST:event_t1b4ActionPerformed

    private void t1b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1b5ActionPerformed
        BT t1b5 =  new BT();
        TextArea1.setText(""+t1b5.dbt1b5());
        control = 105;
    }//GEN-LAST:event_t1b5ActionPerformed

    private void t1b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1b6ActionPerformed
       BT t1b6 =  new BT();
        TextArea1.setText(""+t1b6.dbt1b6());
        control = 106;
    }//GEN-LAST:event_t1b6ActionPerformed

    private void t1b7aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1b7aActionPerformed
        BT t1b7a =  new BT();
        TextArea1.setText(""+t1b7a.dbt1b7a());
        control = 1071;
    }//GEN-LAST:event_t1b7aActionPerformed

    private void t1b7bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1b7bActionPerformed
        BT t1b7b =  new BT();
        TextArea1.setText(""+t1b7b.dbt1b7b());
        control = 1072;
    }//GEN-LAST:event_t1b7bActionPerformed

    private void t1b7cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1b7cActionPerformed
        BT t1b7c =  new BT();
        TextArea1.setText(""+t1b7c.dbt1b7c());
        control = 1073;
    }//GEN-LAST:event_t1b7cActionPerformed

    private void t1b7dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1b7dActionPerformed
       BT t1b7d =  new BT();
        TextArea1.setText(""+t1b7d.dbt1b7d());
        control = 1074;
    }//GEN-LAST:event_t1b7dActionPerformed

    private void t1b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1b8ActionPerformed
        BT t1b8 =  new BT();
        label_nhap.setText("Nhap N: ");
        TextArea1.setText(""+t1b8.dbt1b8());
        control = 108;
    }//GEN-LAST:event_t1b8ActionPerformed

    private void label_nhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_nhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_nhapActionPerformed

    private void t1b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1b9ActionPerformed
        BT t1b9 =  new BT();
        label_nhap.setText("Nhap N: ");
        TextArea1.setText(""+t1b9.dbt1b9());
        control = 109;
    }//GEN-LAST:event_t1b9ActionPerformed

    private void t1b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1b10ActionPerformed
        BT t1b10 =  new BT();
        label_nhap.setText("Nhap N: ");
        TextArea1.setText(""+t1b10.dbt1b10());
        control = 1010;
    }//GEN-LAST:event_t1b10ActionPerformed

    private void t1b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1b11ActionPerformed
        BT t1b11 =  new BT();
        
        TextArea1.setText(""+t1b11.dbt1b11());
        control = 1011;
    }//GEN-LAST:event_t1b11ActionPerformed

    private void t1b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1b12ActionPerformed
        BT t1b12 =  new BT();
        label_nhap.setText("Nhap h: ");
        TextArea1.setText(""+t1b12.dbt1b12());
        control = 1012;
    }//GEN-LAST:event_t1b12ActionPerformed

    private void t2b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2b3ActionPerformed
        BT t2b3 =  new BT();
        label_nhap.setText("Nhap N: ");
        TextArea1.setText(""+t2b3.dbt2b3());
        control = 203;
    }//GEN-LAST:event_t2b3ActionPerformed

    private void t2b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2b1ActionPerformed
        BT t2b1 =  new BT();
        label_nhap.setText("Nhap N: ");
        TextArea1.setText(""+t2b1.dbt2b1());
        control = 201;
    }//GEN-LAST:event_t2b1ActionPerformed

    private void t2b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2b2ActionPerformed
        BT t2b2 =  new BT();
        label_nhap.setText("Nhap N: ");
        TextArea1.setText(""+t2b2.dbt2b2());
        control = 202;
    }//GEN-LAST:event_t2b2ActionPerformed

    private void t2b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2b4ActionPerformed
        BT t2b4 =  new BT();
        label_nhap.setText("Nhap N: ");
        TextArea1.setText(""+t2b4.dbt2b4());
        control = 204;
    }//GEN-LAST:event_t2b4ActionPerformed

    private void t3b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3b1ActionPerformed
        BT t3b1 =  new BT();
        label_nhap.setText("Nhap so phan tu: ");
        btn_nhap2.setText("vi du:2 3 5 7 8");
        btn_nhap.setText("");
        btn_nhap1.setText("");
        TextArea1.setText(""+t3b1.dbt3b1());
        control = 301;
    }//GEN-LAST:event_t3b1ActionPerformed

    private void t3b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3b2ActionPerformed
        BT t3b2 =  new BT();
        label_nhap.setText("Nhap so phan tu: ");
        btn_nhap2.setText("vi du:2 3 5 7 8");
        btn_nhap.setText("");
        btn_nhap1.setText("");
        TextArea1.setText(""+t3b2.dbt3b2());
        control = 302;
    }//GEN-LAST:event_t3b2ActionPerformed
    
    private void text_nhap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nhap2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nhap2ActionPerformed

    private void btn_nhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhapActionPerformed
               
    }//GEN-LAST:event_btn_nhapActionPerformed

    private void text_nhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nhapActionPerformed
        
    }//GEN-LAST:event_text_nhapActionPerformed

    private void t3b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3b3ActionPerformed
        // TODO add your handling code here:
        BT t3b3 =  new BT();
        label_nhap.setText("Nhap so phan tu: ");
        btn_nhap2.setText("vi du:2 3 5 7 8");
        btn_nhap.setText("");
        btn_nhap1.setText("");
        
        TextArea1.setText(""+t3b3.dbt3b3());
        control = 303;
    }//GEN-LAST:event_t3b3ActionPerformed

    private void t3b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3b4ActionPerformed
        // TODO add your handling code here:
        BT t3b4 =  new BT();
        label_nhap.setText("Nhap so phan tu: ");
        btn_nhap2.setText("vi du:2 3 5 7 8");
        btn_nhap.setText("");
        btn_nhap1.setText("");
        TextArea1.setText(""+t3b4.dbt3b4());
        control = 304;
    }//GEN-LAST:event_t3b4ActionPerformed

    private void t3b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3b5ActionPerformed
        // TODO add your handling code here:
        BT t3b5 =  new BT();
        label_nhap.setText("Nhap so phan tu: ");
        btn_nhap2.setText("vi du:2 3 5 7 8");
        btn_nhap.setText("");
        btn_nhap1.setText("");
        TextArea1.setText(""+t3b5.dbt3b5());
        control = 305;
    }//GEN-LAST:event_t3b5ActionPerformed

    private void t3b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3b6ActionPerformed
        // TODO add your handling code here:
        BT t3b6 =  new BT();
        label_nhap.setText("Nhap so phan tu: ");
        btn_nhap2.setText("vi du:2 3 5 7 8");
        btn_nhap.setText("");
        btn_nhap1.setText("");
        TextArea1.setText(""+t3b6.dbt3b6());
        control = 306;
    }//GEN-LAST:event_t3b6ActionPerformed

    private void t3b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3b7ActionPerformed
        // TODO add your handling code here:
        BT t3b7 =  new BT();
        label_nhap.setText("Nhap so phan tu: ");
        btn_nhap2.setText("vi du:2 3 5 7 8");
        btn_nhap.setText("");
        btn_nhap1.setText("");
        TextArea1.setText(""+t3b7.dbt3b7());
        control = 307;
    }//GEN-LAST:event_t3b7ActionPerformed

    private void t3b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3b8ActionPerformed
        // TODO add your handling code here:
        BT t3b8 =  new BT();
        label_nhap.setText("Nhap so phan tu: ");
        btn_nhap2.setText("vi du:2 3 5 7 8");
        btn_nhap.setText("");
        btn_nhap1.setText("");
        TextArea1.setText(""+t3b8.dbt3b8());
        control = 308;
    }//GEN-LAST:event_t3b8ActionPerformed

    private void t3b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3b9ActionPerformed
        BT t3b9 =  new BT();
        label_nhap.setText("Nhap so phan tu:");
        btn_nhap.setText("nhap c");
        btn_nhap2.setText("vi du:2 3 5 7 8");
        btn_nhap1.setText("");
        TextArea1.setText(""+t3b9.dbt3b9());
        control = 309;
    }//GEN-LAST:event_t3b9ActionPerformed

    private void t3b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3b10ActionPerformed
        // TODO add your handling code here:
        BT t3b10 =  new BT();
        label_nhap.setText("Nhap so phan tu:");
        btn_nhap.setText("");
        btn_nhap2.setText("vi du:2 3 5 7 8");
        btn_nhap1.setText("");
        TextArea1.setText(""+t3b10.dbt3b10());
        control = 3010;
    }//GEN-LAST:event_t3b10ActionPerformed

    private void t3b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3b11ActionPerformed
        // TODO add your handling code here:
        BT t3b11 =  new BT();
        label_nhap.setText("Nhap so phan tu:");
        btn_nhap.setText("");
        btn_nhap2.setText("vi du:2 3 5 7 8");
        btn_nhap1.setText("");
        TextArea1.setText(""+t3b11.dbt3b11());
        control = 3011;
    }//GEN-LAST:event_t3b11ActionPerformed

    private void t3b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3b12ActionPerformed
        // TODO add your handling code here:
        BT t3b12 =  new BT();
        label_nhap.setText("So phan tu mang 1");
        btn_nhap.setText("vi du:2 3 5 7 8");
        btn_nhap1.setText("So phan tu mang 2");
        btn_nhap2.setText("vi du:2 3 5 7 8");
        TextArea1.setText(""+t3b12.dbt3b12());
        control = 3012;
    }//GEN-LAST:event_t3b12ActionPerformed

    private void t4b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4b1ActionPerformed
        BT t4b1 =  new BT();
        label_nhap.setText("ho ten:");
        btn_nhap.setText("");
        btn_nhap2.setText("");
        TextArea1.setText(""+t4b1.dbt4b1());
        control = 401;
    }//GEN-LAST:event_t4b1ActionPerformed

    private void t4b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4b2ActionPerformed
        BT t4b2 =  new BT();
        label_nhap.setText("ho ten:");
        btn_nhap.setText("");
        btn_nhap2.setText("");
        TextArea1.setText(""+t4b2.dbt4b2());
        control = 402;
    }//GEN-LAST:event_t4b2ActionPerformed

    private void t4b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4b3ActionPerformed
        BT t4b3 =  new BT();
        label_nhap.setText("ho ten:");
        btn_nhap.setText("");
        btn_nhap2.setText("");
        TextArea1.setText(""+t4b3.dbt4b3());
        control = 403;
    }//GEN-LAST:event_t4b3ActionPerformed

    private void t4b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4b4ActionPerformed
        BT t4b4 =  new BT();
        label_nhap.setText("ho ten:");
        btn_nhap.setText("");
        btn_nhap2.setText("");
        TextArea1.setText(""+t4b4.dbt4b4());
        control = 404;
    }//GEN-LAST:event_t4b4ActionPerformed

    private void t4b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4b5ActionPerformed
        BT t4b5 =  new BT();
        label_nhap.setText("Nhap xau so");
        btn_nhap.setText("");
        btn_nhap2.setText("");
        TextArea1.setText(""+t4b5.dbt4b5());
        control = 405;
    }//GEN-LAST:event_t4b5ActionPerformed

    private void t4b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4b6ActionPerformed
        BT t4b6 =  new BT();
        label_nhap.setText("Nhap xau S");
        btn_nhap.setText("");
        btn_nhap2.setText("");
        TextArea1.setText(""+t4b6.dbt4b6());
        control = 406;
    }//GEN-LAST:event_t4b6ActionPerformed

    private void t4b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4b7ActionPerformed
        BT t4b7 =  new BT();
        label_nhap.setText("Nhap xau S");
        btn_nhap.setText("");
        btn_nhap2.setText("");
        TextArea1.setText(""+t4b7.dbt4b7());
        control = 407;
    }//GEN-LAST:event_t4b7ActionPerformed

    private void t4b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4b8ActionPerformed
        BT t4b8 =  new BT();
        label_nhap.setText("Xau s1");
        btn_nhap.setText("Xau s2");
        btn_nhap2.setText("");
        TextArea1.setText(""+t4b8.dbt4b8());
        control = 408;
    }//GEN-LAST:event_t4b8ActionPerformed

    private void t4b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4b9ActionPerformed
        BT t4b9 =  new BT();
        label_nhap.setText("Xau S");
        btn_nhap.setText("Chi so i");
        btn_nhap1.setText("Chi so j");
        btn_nhap2.setText("");
        TextArea1.setText(""+t4b9.dbt4b9());
        control = 409;
    }//GEN-LAST:event_t4b9ActionPerformed

    private void t4b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4b10ActionPerformed
        BT t4b10 =  new BT();
        label_nhap.setText("So ban trong lop");
        btn_nhap.setText("pham minh-ngoc lan-...");
        btn_nhap1.setText("");
        btn_nhap2.setText("");
        TextArea1.setText(""+t4b10.dbt4b10());
        control = 4010;
    }//GEN-LAST:event_t4b10ActionPerformed

    private void t4b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4b11ActionPerformed
        BT t4b11 =  new BT();
        label_nhap.setText("So ban trong lop");
        btn_nhap.setText("pham minh-ngoc lan-...");
        btn_nhap1.setText("");
        btn_nhap2.setText("");
        TextArea1.setText(""+t4b11.dbt4b11());
        control = 4011;
    }//GEN-LAST:event_t4b11ActionPerformed

    private void t4b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4b12ActionPerformed
        BT t4b12 =  new BT();
        label_nhap.setText("So ban trong lop");
        btn_nhap.setText("pham minh-ngoc lan-...");
        btn_nhap1.setText("");
        btn_nhap2.setText("");
        TextArea1.setText(""+t4b12.dbt4b12());
        control = 4012;
    }//GEN-LAST:event_t4b12ActionPerformed

    private void t4b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4b13ActionPerformed
        BT t4b13 =  new BT();
        label_nhap.setText("So ban trong lop");
        btn_nhap.setText("pham minh-ngoc lan-...");
        btn_nhap1.setText("");
        btn_nhap2.setText("");
        TextArea1.setText(""+t4b13.dbt4b13());
        control = 4013;
    }//GEN-LAST:event_t4b13ActionPerformed

    private void t4b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4b14ActionPerformed
        BT t4b14 =  new BT();
        label_nhap.setText("Nhap N");
        btn_nhap.setText("");
        btn_nhap1.setText("");
        btn_nhap2.setText("");
        TextArea1.setText(""+t4b14.dbt4b14());
        control = 4014;
    }//GEN-LAST:event_t4b14ActionPerformed

    private void t4b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4b15ActionPerformed
        BT t4b15 =  new BT();
        label_nhap.setText("Xau S");
        btn_nhap.setText("Xau s2");
        btn_nhap1.setText("Xau s1");
        TextArea1.setText(""+t4b15.dbt4b15());
        control = 4015;
    }//GEN-LAST:event_t4b15ActionPerformed

    private void t4b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4b16ActionPerformed
        BT t4b16 =  new BT();
        label_nhap.setText("Xau S1");
        btn_nhap.setText("Xau s2");
        btn_nhap1.setText("");
        TextArea1.setText(""+t4b16.dbt4b16());
        control = 4016;
    }//GEN-LAST:event_t4b16ActionPerformed

    private void btn_nhap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nhap1ActionPerformed

    private void text_nhap3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nhap3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nhap3ActionPerformed

    private void btn_nhap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhap2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nhap2ActionPerformed

    private void text_nhap4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nhap4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nhap4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_BT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_BT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_BT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_BT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_BT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Run;
    private javax.swing.JTextArea TextArea1;
    private javax.swing.JTextArea TextArea2;
    private javax.swing.JButton btn_nhap;
    private javax.swing.JButton btn_nhap1;
    private javax.swing.JButton btn_nhap2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton label_nhap;
    private javax.swing.JButton t1b1;
    private javax.swing.JButton t1b10;
    private javax.swing.JButton t1b11;
    private javax.swing.JButton t1b12;
    private javax.swing.JButton t1b2;
    private javax.swing.JButton t1b3;
    private javax.swing.JButton t1b4;
    private javax.swing.JButton t1b5;
    private javax.swing.JButton t1b6;
    private javax.swing.JButton t1b7a;
    private javax.swing.JButton t1b7b;
    private javax.swing.JButton t1b7c;
    private javax.swing.JButton t1b7d;
    private javax.swing.JButton t1b8;
    private javax.swing.JButton t1b9;
    private javax.swing.JButton t2b1;
    private javax.swing.JButton t2b2;
    private javax.swing.JButton t2b3;
    private javax.swing.JButton t2b4;
    private javax.swing.JButton t3b1;
    private javax.swing.JButton t3b10;
    private javax.swing.JButton t3b11;
    private javax.swing.JButton t3b12;
    private javax.swing.JButton t3b2;
    private javax.swing.JButton t3b3;
    private javax.swing.JButton t3b4;
    private javax.swing.JButton t3b5;
    private javax.swing.JButton t3b6;
    private javax.swing.JButton t3b7;
    private javax.swing.JButton t3b8;
    private javax.swing.JButton t3b9;
    private javax.swing.JButton t4b1;
    private javax.swing.JButton t4b10;
    private javax.swing.JButton t4b11;
    private javax.swing.JButton t4b12;
    private javax.swing.JButton t4b13;
    private javax.swing.JButton t4b14;
    private javax.swing.JButton t4b15;
    private javax.swing.JButton t4b16;
    private javax.swing.JButton t4b2;
    private javax.swing.JButton t4b3;
    private javax.swing.JButton t4b4;
    private javax.swing.JButton t4b5;
    private javax.swing.JButton t4b6;
    private javax.swing.JButton t4b7;
    private javax.swing.JButton t4b8;
    private javax.swing.JButton t4b9;
    private javax.swing.JTextField text_nhap;
    private javax.swing.JTextField text_nhap2;
    private javax.swing.JTextField text_nhap3;
    private javax.swing.JTextField text_nhap4;
    // End of variables declaration//GEN-END:variables
}
